make all workflow read only

diff --git a/community_images/common/templates/readme_updater.yml.j2 b/community_images/common/templates/readme_updater.yml.j2
--- a/community_images/common/templates/readme_updater.yml.j2
+++ b/community_images/common/templates/readme_updater.yml.j2
@@ -18,9 +18,6 @@ jobs:
     runs-on: ubuntu-latest
     environment: actions-cicd
 
-    permissions:
-      contents: write
-
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
@@ -28,13 +25,11 @@ jobs:
       - name: Generate new readme and image files
         run: ./scripts/image_generator.sh
 
-      # Push all the changes
-      - name: Push changes
+      - name: Check if new changes detected
         run: |
           if [[ $(git status --porcelain) ]]; then
-            git config user.name "Rapidfort Readme Bot"
-            git config user.email "info@rapidfort.com"
-            git add . && git commit -am "Update README.md via script" --signoff && git push
+            echo "Fail as the image_generator script was not run"
+            exit 1
           fi
 
       - name: Update readme for dockerhub
