Addressed logs not printing
Signed-off-by: vasus2 <vasus2@illinois.edu>

diff --git a/.github/workflows/ib_pipelines_check.yml b/.github/workflows/ib_pipelines_check.yml
--- a/.github/workflows/ib_pipelines_check.yml
+++ b/.github/workflows/ib_pipelines_check.yml
@@ -2,8 +2,7 @@ name: IB Pipelines Tracker
 
 on:
   schedule:
-  - cron: '0 0 * * *'
-
+    - cron: '0 0 * * *'
   workflow_dispatch:
 
 permissions: read-all
@@ -19,11 +18,19 @@ jobs:
 
       - name: Run Pipeline Check
         id: pipeline_check_step
-        run: python3 ./scripts/ib_pipelines_check.py | tee ib_tracker_logs.txt | echo "::set-output name=workflow-status::${PIPESTATUS[0]}"
-
-      - name: Check Workflow Status
         run: |
-          if [[ "${{ steps.pipeline_check_step.outputs.workflow-status }}" != "0" ]]; then
-            echo "Pipeline check failed."
-            exit 1
-          fi
+          python3 ./scripts/ib_pipelines_check.py | tee ib_tracker_logs.txt
+          exit ${PIPESTATUS[0]}
+        continue-on-error: true
+
+      - name: Set job status
+        if: steps.pipeline_check_step.outcome == 'failure'
+        run: |
+          echo "Pipeline check failed."
+          exit 1
+
+      - name: Upload logs
+        uses: actions/upload-artifact@v3
+        with:
+          name: pipeline-logs
+          path: ib_tracker_logs.txt
